use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::HashMap;

use super::{parse_size_dimensions, ImageProviderAdapter, ImageRequestPayload, ImageResponseData};
use crate::image_generator::types::ImageGenerationRequest;

/// OpenRouter's unified Image API (`/api/v1/images`). This is the path OpenRouter
/// recommends for image workloads; it returns the generated bytes directly instead of
/// wrapping them in a chat completion.
pub struct OpenRouterAdapter;

/// The older chat-completions path (`modalities: ["image"]`). Kept as a fallback for
/// models that OpenRouter does not expose through the Image API.
pub struct OpenRouterChatAdapter;

const IMAGE_ASPECT_RATIOS: &[(&str, f64)] = &[
    ("1:1", 1.0),
    ("4:5", 0.8),
    ("5:4", 1.25),
    ("3:4", 0.75),
    ("4:3", 4.0 / 3.0),
    ("2:3", 2.0 / 3.0),
    ("3:2", 1.5),
    ("9:16", 9.0 / 16.0),
    ("16:9", 16.0 / 9.0),
    ("9:21", 9.0 / 21.0),
    ("21:9", 21.0 / 9.0),
];

const IMAGE_QUALITIES: &[&str] = &["auto", "low", "medium", "high"];

fn openrouter_headers(
    api_key: &str,
    extra: Option<&HashMap<String, String>>,
) -> HashMap<String, String> {
    let mut headers = HashMap::new();
    headers.insert("Authorization".into(), format!("Bearer {}", api_key));
    headers.insert("Content-Type".into(), "application/json".into());
    headers.insert("HTTP-Referer".into(), "https://www.lettuceai.app/".into());

    if let Some(extra) = extra {
        for (k, v) in extra.iter() {
            headers.insert(k.clone(), v.clone());
        }
    }

    headers
}

fn openrouter_v1_base(base_url: &str) -> String {
    let trimmed = base_url.trim_end_matches('/');
    if trimmed.ends_with("/v1") {
        trimmed.to_string()
    } else {
        format!("{}/v1", trimmed)
    }
}

fn nearest_aspect_ratio(size: Option<&str>) -> Option<&'static str> {
    let size = size?;
    let (width, height) = parse_size_dimensions(Some(size), 0, 0);
    if width == 0 || height == 0 {
        return None;
    }
    let ratio = width as f64 / height as f64;
    IMAGE_ASPECT_RATIOS
        .iter()
        .min_by(|(_, a), (_, b)| {
            (a - ratio)
                .abs()
                .partial_cmp(&(b - ratio).abs())
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .map(|(label, _)| *label)
}

fn image_api_quality(quality: Option<&str>) -> Option<&'static str> {
    let quality = quality?.trim().to_ascii_lowercase();
    IMAGE_QUALITIES
        .iter()
        .copied()
        .find(|candidate| *candidate == quality)
}

fn image_api_payload(request: &ImageGenerationRequest) -> Value {
    let mut payload = json!({
        "model": request.model,
        "prompt": request.prompt,
    });

    if let Some(n) = request.n.filter(|n| *n > 0) {
        payload["n"] = json!(n);
    }
    if let Some(aspect_ratio) = nearest_aspect_ratio(request.size.as_deref()) {
        payload["aspect_ratio"] = json!(aspect_ratio);
    }
    if let Some(quality) = image_api_quality(request.quality.as_deref()) {
        payload["quality"] = json!(quality);
    }

    let references: Vec<Value> = request
        .input_images
        .iter()
        .flatten()
        .filter(|image| !image.trim().is_empty())
        .map(|image| {
            json!({
                "type": "image_url",
                "image_url": { "url": image },
            })
        })
        .collect();
    if !references.is_empty() {
        payload["input_references"] = Value::Array(references);
    }

    payload
}

#[derive(Deserialize)]
struct ImageApiResponse {
    #[serde(default)]
    data: Vec<ImageApiImage>,
}

#[derive(Deserialize)]
struct ImageApiImage {
    #[serde(default)]
    b64_json: Option<String>,
    #[serde(default)]
    url: Option<String>,
    #[serde(default)]
    media_type: Option<String>,
    #[serde(default)]
    revised_prompt: Option<String>,
}

fn parse_image_api_response(response: Value) -> Result<Vec<ImageResponseData>, String> {
    let parsed: ImageApiResponse = serde_json::from_value(response).map_err(|e| {
        crate::utils::err_msg(
            module_path!(),
            line!(),
            format!("Failed to parse response: {}", e),
        )
    })?;

    let mut results = Vec::new();
    for image in parsed.data {
        let text = image
            .revised_prompt
            .filter(|value| !value.trim().is_empty());
        if let Some(b64) = image.b64_json.filter(|value| !value.is_empty()) {
            let b64_json = if b64.starts_with("data:") {
                b64
            } else {
                let media_type = image
                    .media_type
                    .as_deref()
                    .filter(|value| value.starts_with("image/"))
                    .unwrap_or("image/png");
                format!("data:{};base64,{}", media_type, b64)
            };
            results.push(ImageResponseData {
                url: None,
                b64_json: Some(b64_json),
                text,
            });
        } else if let Some(url) = image.url.filter(|value| !value.is_empty()) {
            results.push(ImageResponseData {
                url: Some(url),
                b64_json: None,
                text,
            });
        }
    }

    if results.is_empty() {
        return Err(crate::utils::err_msg(
            module_path!(),
            line!(),
            "No images generated in response",
        ));
    }

    Ok(results)
}

/// OpenRouter answers with 400/404 when a model is not served through the Image API.
/// Those requests are worth retrying through chat completions, which is how image
/// output used to be requested and still works for chat-style image models.
fn should_fall_back_to_chat(status: u16, body: &str) -> bool {
    match status {
        404 => true,
        400 | 422 => {
            let body = body.to_ascii_lowercase();
            ["model", "endpoint", "not supported", "unsupported", "not available"]
                .iter()
                .any(|needle| body.contains(needle))
        }
        _ => false,
    }
}

impl ImageProviderAdapter for OpenRouterAdapter {
    fn endpoint(&self, base_url: &str, _request: &ImageGenerationRequest) -> String {
        format!("{}/images", openrouter_v1_base(base_url))
    }

    fn required_auth_headers(&self) -> &'static [&'static str] {
        &["Authorization"]
    }

    fn headers(
        &self,
        api_key: &str,
        extra: Option<&HashMap<String, String>>,
    ) -> HashMap<String, String> {
        openrouter_headers(api_key, extra)
    }

    fn payload(&self, request: &ImageGenerationRequest) -> Result<ImageRequestPayload, String> {
        Ok(ImageRequestPayload::Json(image_api_payload(request)))
    }

    fn parse_response(&self, response: Value) -> Result<Vec<ImageResponseData>, String> {
        parse_image_api_response(response)
    }

    fn fallback_adapter(
        &self,
        status: u16,
        body: &str,
    ) -> Option<Box<dyn ImageProviderAdapter>> {
        should_fall_back_to_chat(status, body)
            .then(|| Box::new(OpenRouterChatAdapter) as Box<dyn ImageProviderAdapter>)
    }
}

#[derive(Serialize)]
struct OpenRouterMessage<'a> {
    role: &'a str,
    content: Value,
}

#[derive(Serialize)]
struct OpenRouterRequest<'a> {
    model: &'a str,
    messages: Vec<OpenRouterMessage<'a>>,
    modalities: Vec<&'a str>,
}

#[derive(Deserialize)]
struct OpenRouterResponse {
    choices: Vec<OpenRouterChoice>,
}

#[derive(Deserialize)]
struct OpenRouterChoice {
    message: OpenRouterResponseMessage,
}

#[derive(Deserialize)]
struct OpenRouterResponseMessage {
    #[serde(default)]
    content: Option<String>,
    #[serde(default)]
    images: Vec<OpenRouterImage>,
}

#[derive(Deserialize)]
struct OpenRouterImage {
    #[serde(rename = "type")]
    _type: Option<String>,
    image_url: OpenRouterImageUrl,
}

#[derive(Deserialize)]
struct OpenRouterImageUrl {
    url: String,
}

impl ImageProviderAdapter for OpenRouterChatAdapter {
    fn endpoint(&self, base_url: &str, _request: &ImageGenerationRequest) -> String {
        format!("{}/chat/completions", openrouter_v1_base(base_url))
    }

    fn required_auth_headers(&self) -> &'static [&'static str] {
        &["Authorization"]
    }

    fn headers(
        &self,
        api_key: &str,
        extra: Option<&HashMap<String, String>>,
    ) -> HashMap<String, String> {
        openrouter_headers(api_key, extra)
    }

    fn payload(&self, request: &ImageGenerationRequest) -> Result<ImageRequestPayload, String> {
        let content = if let Some(input_images) = &request.input_images {
            let mut parts = vec![json!({
                "type": "text",
                "text": request.prompt,
            })];

            for image in input_images {
                parts.push(json!({
                    "type": "image_url",
                    "image_url": {
                        "url": image,
                    }
                }));
            }

            Value::Array(parts)
        } else {
            Value::String(request.prompt.clone())
        };

        let message = OpenRouterMessage {
            role: "user",
            content,
        };

        let mut modalities: Vec<&str> = vec!["image"];
        let supports_text = match &request.output_modalities {
            Some(scopes) => scopes.iter().any(|s| s.eq_ignore_ascii_case("text")),
            None => false,
        };
        if supports_text {
            modalities.push("text");
        }

        let req = OpenRouterRequest {
            model: &request.model,
            messages: vec![message],
            modalities,
        };

        Ok(ImageRequestPayload::Json(
            serde_json::to_value(req).unwrap_or_else(|_| json!({})),
        ))
    }

    fn parse_response(&self, response: Value) -> Result<Vec<ImageResponseData>, String> {
        let or_response: OpenRouterResponse = serde_json::from_value(response).map_err(|e| {
            crate::utils::err_msg(
                module_path!(),
                line!(),
                format!("Failed to parse response: {}", e),
            )
        })?;

        if or_response.choices.is_empty() {
            return Err(crate::utils::err_msg(
                module_path!(),
                line!(),
                "No choices in response",
            ));
        }

        let mut results = Vec::new();

        for choice in or_response.choices {
            let text = choice.message.content.filter(|s| !s.is_empty());

            if !choice.message.images.is_empty() {
                for img in choice.message.images {
                    let image_url = img.image_url.url;

                    let (url, b64_json) = if image_url.starts_with("data:") {
                        (None, Some(image_url))
                    } else {
                        (Some(image_url), None)
                    };

                    results.push(ImageResponseData {
                        url,
                        b64_json,
                        text: text.clone(),
                    });
                }
            } else if let Some(t) = text {
                results.push(ImageResponseData {
                    url: None,
                    b64_json: None,
                    text: Some(t),
                });
            }
        }

        if results.is_empty() {
            return Err(crate::utils::err_msg(
                module_path!(),
                line!(),
                "The model finished without returning an image. Try the request again or pick a different model.",
            ));
        }

        Ok(results)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request_with(size: Option<&str>, input_images: Option<Vec<String>>) -> ImageGenerationRequest {
        ImageGenerationRequest {
            prompt: "a lettuce".to_string(),
            model: "openai/gpt-5.4-image-2".to_string(),
            provider_id: "openrouter".to_string(),
            credential_id: "cred".to_string(),
            advanced_model_settings: None,
            input_images,
            mask_image: None,
            loras: None,
            output_modalities: None,
            size: size.map(str::to_string),
            quality: None,
            style: None,
            n: Some(1),
            session_id: None,
            character_id: None,
            character_name: None,
            usage_source: None,
        }
    }

    #[test]
    fn image_api_endpoint_is_built_from_the_provider_base_url() {
        let request = request_with(None, None);
        assert_eq!(
            OpenRouterAdapter.endpoint("https://openrouter.ai/api", &request),
            "https://openrouter.ai/api/v1/images"
        );
        assert_eq!(
            OpenRouterAdapter.endpoint("https://openrouter.ai/api/v1/", &request),
            "https://openrouter.ai/api/v1/images"
        );
        assert_eq!(
            OpenRouterChatAdapter.endpoint("https://openrouter.ai/api", &request),
            "https://openrouter.ai/api/v1/chat/completions"
        );
    }

    #[test]
    fn image_api_payload_maps_size_to_the_nearest_aspect_ratio_and_attaches_references() {
        let request = request_with(
            Some("832x1216"),
            Some(vec!["data:image/png;base64,AAAA".to_string()]),
        );
        let payload = image_api_payload(&request);
        assert_eq!(payload["model"], "openai/gpt-5.4-image-2");
        assert_eq!(payload["aspect_ratio"], "2:3");
        assert_eq!(payload["n"], 1);
        assert_eq!(payload["input_references"][0]["type"], "image_url");
        assert_eq!(
            payload["input_references"][0]["image_url"]["url"],
            "data:image/png;base64,AAAA"
        );
        assert!(payload.get("size").is_none());
        assert!(payload.get("quality").is_none());
    }

    #[test]
    fn image_api_payload_skips_optional_fields_when_absent() {
        let request = request_with(None, None);
        let payload = image_api_payload(&request);
        assert!(payload.get("aspect_ratio").is_none());
        assert!(payload.get("input_references").is_none());
    }

    #[test]
    fn image_api_response_is_wrapped_in_a_data_url() {
        let results = parse_image_api_response(json!({
            "data": [{ "b64_json": "QUJD", "media_type": "image/webp" }],
            "usage": { "total_tokens": 10 }
        }))
        .unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(
            results[0].b64_json.as_deref(),
            Some("data:image/webp;base64,QUJD")
        );
        assert!(results[0].url.is_none());
    }

    #[test]
    fn image_api_response_without_images_is_an_error() {
        let err = parse_image_api_response(json!({ "data": [] })).unwrap_err();
        assert!(err.contains("No images"));
    }

    #[test]
    fn chat_fallback_only_triggers_for_unsupported_model_errors() {
        assert!(should_fall_back_to_chat(404, ""));
        assert!(should_fall_back_to_chat(
            400,
            r#"{"error":{"message":"Model is not supported by the images endpoint"}}"#
        ));
        assert!(!should_fall_back_to_chat(400, r#"{"error":{"message":"Invalid prompt"}}"#));
        assert!(!should_fall_back_to_chat(401, "unauthorized"));
        assert!(!should_fall_back_to_chat(500, "model failed"));
    }

    #[test]
    fn chat_response_without_images_or_text_reports_a_readable_error() {
        let err = OpenRouterChatAdapter
            .parse_response(json!({
                "choices": [{
                    "finish_reason": "stop",
                    "message": { "content": null, "role": "assistant" }
                }]
            }))
            .unwrap_err();
        assert!(err.contains("without returning an image"));
    }
}
